name: Create ALF File

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version: [2018.4.12f1]
    steps:
    - uses: pCYSl5EDgo/setup-unity@master
      with:
        unity-version: ${{ matrix.unity-version }}
    #- run: wget https://beta.unity3d.com/download/497f083a43af/UnitySetup -O UnitySetUp
    #- run: sudo chmod +x UnitySetUp
    #- run: ./UnitySetUp --unattended --install-location=/opt/Unity --verbose --download-location=/tmp/unity --components=Unity
    - run: ls -l
    - run: ls -l /opt/
    - run: ls -l /opt/Unity-${{ matrix.unity-version }}/
    - run: ls -l /opt/Unity-${{ matrix.unity-version }}/Editor/
    - run: /opt/Unity-${{ matrix.unity-version }}/Editor/Unity -quit -batchmode -nographics -logfile -createManualActivationFile || exit 0
    - run: cat Unity_v${{ matrix.unity-version }}.alf
