name: Create ALF File

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version: [2018.4.12f1]
    steps:
    - uses: pCYSl5EDgo/setup-unity@master
      with:
        unity-version: 2018.4.13f1
    - run: |
        ls -l /
        ls -l /opt/
        ls -l /opt/Unity/
        ls -l /opt/Unity/Editor/
