name: Create ALF File

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        unity-version: [2018.4.12f1]
    steps:
    - run: |
        gem install u3d
        u3d install ${{ matrix.unity-version }} --packages Unity
    - run: dir "C:/Program Files/Unity_2018.4.12f1"
