name: Create ALF File

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        unity-version: [2018.4.12f1]
    steps:
    - run: |
        wget "https://beta.unity3d.com/download/59ddc4c59b4f/UnitySetup-2018.4.12f1" -O ./UnitySetUp
        ls -l
        sudo chmod +x UnitySetUp
    - run: echo y | ./UnitySetUp \
        --unattended \
        --install-location=/opt/Unity \
        --verbose \
        --download-location=/tmp/unity \
        --components=Unity
    - run: rm UnitySetup && \
        rm -rf /tmp/unity && \
        rm -rf /root/.local/share/Trash/*
    - run: ls -l /opt
    - run: ls -l /opt/Unity
